export const reactArray = [
  {
    _id: 1,
    link: "basics",
    title: "Basics",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 2,
    link: "props",
    title: "Props",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 3,
    link: "nesting",
    title: "Nesting",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 4,
    link: "setup",
    title: "Setup",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 5,
    link: "state",
    title: "State",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 6,
    link: "arrays",
    title: "Arrays",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 7,
    link: "effect",
    title: "useEffect & Fetch",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 8,
    link: "storage",
    title: "Local Storage",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 9,
    link: "c-hooks",
    title: "Custom Hooks",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 10,
    link: "global-state",
    title: "Global State",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 11,
    link: "inmu-state",
    title: "Inmutable State",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 12,
    link: "fetching",
    title: "Data Fetching",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
  {
    _id: 13,
    link: "testing",
    title: "Testing",
    intro: "testIntro",
    moreIntro: "testmoreIntro",
    codeA: "testCodeA",
    codeB: "testCodeB",
    codeC: "testCodeC",
    subtitle: "testSubtitle",
    subIntro: "testsubIntro",
    moreSubIntro: "testmoreSubIntro",
    codeSubA: "testcodeSubA",
    codeSubB: "testcodeSubB",
    codeSubC: "testcodeSubC",
    textA: "testTextA",
    codeTextAA: "testcodeTextAA",
    codeTextAB: "testcodeTextAB",
    codeTextAC: "testcodeTextAC",
    textB: "testtextB",
    codeTextBA: "testcodeTextBA",
    codeTextBB: "testcodeTextBB",
    codeTextBC: "testcodeTextBC",
  },
];
